"""Single-pass 6-channel prompt generator & validator for the Outreach Studio."""

from __future__ import annotations

import json
import logging
import uuid

from sqlalchemy.orm import Session

from app.models.repository import RepositoryItem
from app.models.studio import StudioChannelContent, StudioJob
from app.services.llm_gateway import generate

logger = logging.getLogger(__name__)

CHANNEL_DEFINITIONS = [
    {"channel": "web",        "label": "Website article",   "icon": "◒"},
    {"channel": "linkedin",   "label": "LinkedIn",          "icon": "in"},
    {"channel": "instagram",  "label": "Instagram",         "icon": "◎"},
    {"channel": "x",          "label": "X post",            "icon": "𝕏"},
    {"channel": "education",  "label": "Educational post",  "icon": "✦"},
    {"channel": "newsletter", "label": "Newsletter",        "icon": "✉"},
]

STUDIO_SYSTEM_PROMPT = """\
You are a science communication specialist for NCPOR (India's polar research centre).
Given the source text from a polar research document, generate tailored content \
for 6 outreach channels.

Return a JSON object with exactly these keys:
- "web": Headline + long-form structured article paragraph (200-300 words).
- "linkedin": Professional executive summary with 2-3 relevant hashtags (100-150 words).
- "instagram": Engaging visual narrative caption with a call-to-action (80-120 words).
- "x": Punchy post under 280 characters.
- "education": "Did You Know?" curiosity-focused framing for students (80-120 words).
- "newsletter": Digest-style paragraph with key takeaways (100-150 words).

RULES:
1. Stay grounded in the source text. Do not add facts not present in the source.
2. Adapt tone for each channel's audience.
3. Return raw JSON only. No markdown code fences.
"""


async def generate_studio_job(repository_item_id: str, db: Session) -> StudioJob:
    """Create a ``StudioJob`` with 6 channel drafts generated by the LLM."""

    # Fetch source item
    item = (
        db.query(RepositoryItem)
        .filter(RepositoryItem.id == repository_item_id)
        .first()
    )
    if not item:
        raise ValueError(f"Repository item '{repository_item_id}' not found")

    # Build source text (cap at 8 000 chars to stay within context window)
    source_text = item.raw_text or item.summary or item.title
    if len(source_text) > 8000:
        source_text = source_text[:8000] + "…"

    user_prompt = (
        f'Source document: "{item.title}" ({item.type}, {item.year}, {item.region})\n\n'
        f"{source_text}"
    )

    # Call LLM
    try:
        raw_response = await generate(
            system_prompt=STUDIO_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            temperature=0.4,
        )

        # Parse response — strip code fences if present
        cleaned = raw_response.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("\n", 1)[1] if "\n" in cleaned else cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()

        drafts: dict[str, str] = json.loads(cleaned)
    except Exception as exc:
        logger.error("Studio generation failed: %s", exc)
        drafts = {
            ch["channel"]: f"[Draft pending — LLM generation failed. Source: {item.title}]"
            for ch in CHANNEL_DEFINITIONS
        }

    # Persist StudioJob + 6 channel records
    job_id = str(uuid.uuid4())
    job = StudioJob(id=job_id, repository_item_id=repository_item_id, status="Drafted")
    db.add(job)

    for ch_def in CHANNEL_DEFINITIONS:
        ch_name = ch_def["channel"]
        db.add(
            StudioChannelContent(
                id=str(uuid.uuid4()),
                job_id=job_id,
                channel=ch_name,
                label=ch_def["label"],
                icon=ch_def["icon"],
                content=drafts.get(ch_name, f"[No content generated for {ch_name}]"),
                approved=False,
            )
        )

    db.commit()
    db.refresh(job)
    return job
